name: tests-orders
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
<<<<<<< HEAD:.github/workflows/tests.yml
      - run: cd ticketing/auth && npm install && npm run test:ci
=======
      - run: cd ticketing/orders && npm install && npm run test:ci
>>>>>>> master:.github/workflows/tests-orders.yaml
